export const TOKENS = {
  USER_REPOSITORY: 'USER_REPOSITORY',
  DATA_SOURCE: 'DATA_SOURCE',
  LOG_REPOSITORY: 'LOG_REPOSITORY',
};

export const jwtConstants = {
  secret:
    'DO NOT USE THIS VALUE. INSTEAD, CREATE A COMPLEX SECRET AND KEEP IT SAFE OUTSIDE OF THE SOURCE CODE.',
};
